### ISSUE TITLE
bundle/python-mode/plugin/pymode.vim

### ISSUE THREAD

**Issue by dreamsincode** [python-mode/python-mode#784] opened 2017-07-30 07:46 UTC
Receiving error bundle/python-mode/plugin/pymode.vim
 when I try to run bundle/python-mode/plugin/pymode.vim
When I go to the path to pymode in the troubleshooting steps, it tells me it cannot find debug.vim. Where is it usually located? 
Thanks (and sorry if I missed something)

**Comment by smheidrich** [comment] 2017-09-04 20:37
For me ``debug.vim`` it's right in the python-mode repo directory, e.g. ``~/.vim/bundle/python-mode/debug.vim``. If you haven't made any important changes to the repo, I'd suggest just deleting the ``python-mode`` directory and reinstalling it using ``:PluginInstall``.

**Comment by fmv1992** [comment] 2017-11-19 00:47
Closing due to lack of information on what the problem is.

Feel free to reopen the issue.

**Closed by fmv1992** 2017-11-19 00:47 UTC
