### ISSUE TITLE
Error message whenever I save a Python file

### ISSUE THREAD

**Issue by mrbig033** [python-mode/python-mode#864] opened 2018-03-17 04:35 UTC
```
Error detected while processing function pymode#buffer_post_write[10]..pymode#lint#check[11]..provider#python3#Call:  
line   18:                                                                                                            
Traceback (most recent call last):                                                                                    
  File "<string>", line 1, in <module>                                                                                
  File "/home/mrbig/.config/nvim/plugins/plugged/python-mode/pymode/lint.py", line 46, in code_check                  
    options.linters_params['pylint']['clear_cache'] = True                                                            
KeyError: 'pylint'   
```
[`call pymode#troubleshooting#test()`](https://hastebin.com/oximuleqan.bash) shows no warnings.
I'm on MX Linux 17, NVIM v0.2.3-820-g9cefd83cc. Both python and python3 are on /usr/bin. My [nvim configuration files](https://github.com/mrbig033/dotfiles/tree/master/nvim).

**Comment by diraol** [comment] 2018-03-17 11:54
@mrbig033 , please follow the Install instructions on the README.md:

https://github.com/python-mode/python-mode#how-to-install

**Comment by mrbig033** [comment] 2018-03-17 13:39
I did that already. The only difference was that I installed it witch vim-plug.

**Comment by diraol** [comment] 2018-03-17 14:22
> Okay, installed it with Pathogen and now it works.

No matter if you use pathogen or vim-plug you need to go into the `python-mode` directory and run the `git submodule update --init --recursive` command.

 > Another thing: when I run python code that requires user input, is there a way for me insert it?

How so? I didn't understand the question and its relationship with `python-mode` vim plugin.

**Comment by mrbig033** [comment] 2018-03-17 15:56
I had tried the command `git submodule update --init --recursive` before with the vim-plug install and it did not work, but it did after I installed python-mode with Pathogen. Maybe I made some mistake before.
Sorry about the cryptic question, english is not my first language: is it possible to run the code interactively (like on the Python Idle shell, for example) in such a way that allows me to input strings into the program while it is running?

**Comment by diraol** [comment] 2018-03-17 18:37
No problem, English isn't my first language neither.

I am not sure about this, but from this issue (#122) I imagine that it is possible.....

The answer may be on this file (https://github.com/python-mode/python-mode/blob/develop/doc/pymode.txt) or on this one (https://github.com/python-mode/python-mode/blob/develop/autoload/pymode/run.vim).

**Comment by diraol** [comment] 2018-03-17 18:38
I'll close this issue because the main subject is already resolved.

If you need further assistance, please, open another issue. ;)

**Closed by diraol** 2018-03-17 18:38 UTC

**Comment by mnoukhov** [comment] 2018-03-28 21:26
I have the same issue and I don't understand why I need to use Pathogen instead of vim-plug.

One issue is that this may be caused by some combination of neovim and vim-plug, because this error doesn't appear with standard vim. Do you have any idea what may be the problem?
