### ISSUE TITLE
Rope refactoring doesn't work properly

### ISSUE THREAD

**Issue by blayz3r** [python-mode/python-mode#1100] opened 2020-08-20 14:57 UTC
**Extract x + 3 to z**
![image](https://user-images.githubusercontent.com/12205650/90788332-b58b3f00-e2d3-11ea-8641-504ccd391365.png)

**Result**
![image](https://user-images.githubusercontent.com/12205650/90788419-ca67d280-e2d3-11ea-95de-92641ffe6b98.png)

**Issues:**
Does it once
3 is still in y

**Comment by diraol** [comment] 2020-08-21 22:49
Sorry, I am not sure if I understood...

What's the outcome you were expecting to have?

**Comment by blayz3r** [comment] 2020-08-22 03:36
It should just be z + 4, since x + 3 = z

**Comment by blayz3r** [comment] 2020-08-22 03:38
If there was another x + 3 in the file it would be ignored

**Comment by diraol** [comment] 2020-08-22 13:36
Well, in your sample you have `y = x * 3 + 4`, not `y = x + 3 + 4` .....

**Comment by blayz3r** [comment] 2020-08-22 16:25
Yes you but can test x + 3,  x + 3. It doesn't work for either

**Comment by blayz3r** [comment] 2020-09-04 03:54
@diraol any insight?

**Comment by diraol** [comment] 2020-09-04 20:19
Hi @blayz3r sorry for not answering before, It has been very hard to free some time to `python-mode`.

I've tested here and, indeed, this functionality is not working.

I guess this is an issue with python-mode itself. Either with the ExtractVariable class

https://github.com/python-mode/python-mode/blob/develop/pymode/rope.py#L583-L604

or the Refactoring class

https://github.com/python-mode/python-mode/blob/develop/pymode/rope.py#L443-L511

Have you tested other Refactor methods to check if they work properly? (So we can know if the Refactor class seems to be working)?

**Comment by blayz3r** [comment] 2020-09-04 21:12
Sure no problem, I'll do some testing and report back.

**Comment by lieryan** [comment] 2020-09-05 14:56
I can reproduce this when Vim's is linked to Python 3.8 but not on 3.7 and 3.6. I tested with all those mentioned Python versions on NeoVim because it's much easier to switch Python version in Neovim and I tested Vim only with Python 3.8, but all evidence points that this should be the case in Vim as well.

I am pretty sure this is a bug in [rope](https://github.com/python-rope/rope) which is not yet compatible with 3.8. Running the latest version of rope's (0.17.0) own unittest on Python 3.8 fails with a large number of unittest failures that looks very similar to what we had here.

In the meantime, until rope is updated to support Python 3.8 properly, you should be able to workaround the issue by downgrading your Vim to a version that uses Python 3.7 or earlier, or if you're using Neovim, you can point `let g:python3_host_prog = '/path/to/python3.7'` to Python 3.7 or earlier.

**Comment by lieryan** [comment] 2020-10-08 16:18
This should now be fixed in latest version of rope (master/0.18.0). You can update the submodule/rope on your local install if you need this now, or wait until python-mode updates its submoduled rope.

**Comment by diraol** [comment] 2020-10-08 17:44
Thanks for the heads up!

I've updated all python-mode submodules to the latest released version and made a new release of python-mode ;)

**Comment by diraol** [comment] 2020-10-08 18:55
(By the way, while updating the submodules I've added a new submodule dependency there, `toml` for autopep8)

**Comment by blayz3r** [comment] 2020-10-08 19:55
Thanks

**Closed as completed** 2020-10-08 19:55 UTC
