### ISSUE TITLE
Can't set pymode_python

### ISSUE THREAD

**Issue by neapel** [python-mode/python-mode#469] opened 2014-08-11 23:43 UTC
I've installed pymode using `NeoBundle 'klen/python-mode'` (updated just now).

Setting `let g:pymode_python = 'python'` (or saying nothing) works as expected, but gives me python2 errors for python3 files.

When I say `let g:pymode_python = 'python3'`, I get this error when opening a python file:

```
Error detected while processing function pymode#init:
line    9:
E319: Sorry, the command is not available in this version: python3 import sys, vim
line   10:
E319: Sorry, the command is not available in this version: python3 sys.path.insert(0, vim.eval('a:plugin_root'))
line   11:
E319: Sorry, the command is not available in this version: python3 sys.path = vim.eval('a:paths') + sys.path
Error detected while processing autoload/pymode/virtualenv.vim:
line    3:
E319: Sorry, the command is not available in this version: python3 from pymode.virtualenv import enable_virtualenv
Error detected while processing function pymode#breakpoint#init:
line   15:
E319: Sorry, the command is not available in this version: python3 << EOF
line   17:
E492: Not an editor command: from imp import find_module
line   19:
E110: Missing ')'
E15: Invalid expression: ('pudb', 'ipdb'):
line   20:
E488: Trailing characters:     try:
line   28:
E170: Missing :endfor
Error detected while processing autoload/pymode/lint.vim:
line    1:
E319: Sorry, the command is not available in this version: python3 from pymode.lint import code_check
```

And `let g:pymode_python = 'disable'`, gives this (vim is compiled with +python)

```
[Pymode]: error: Pymode requires vim compiled with +python. Most of features will be disabled.
Error detected while processing autoload/pymode/virtualenv.vim:
line    3:
E121: Undefined variable: from
E15: Invalid expression: from pymode.virtualenv import enable_virtualenv
Error detected while processing ftplugin/python/pymode.vim:
line   12:
E121: Undefined variable: from
E15: Invalid expression: from pymode.utils import patch_paths
```

Using MacVim 7.4 or vim 7.3; python3 3.4.1; python 2.7.6
##

**Comment by Whiothes** [comment] 2016-07-05 22:51
```
$ vim --version| grep python
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
```
But, I have the same problem.

**Comment by L-Cafe** [comment] 2017-12-27 19:09
> homebrew doesn't support both at once

Homebrew absolutely supports both at once, but they're dynamically loaded, and if you load either, you cannot load the other one.

This is still not solved, my Vim is -python and +python3, Vim shows lots of errors when starting up, exactly like @neapel posted.

Is there anything we can do?

**Comment by fmv1992** [comment] 2018-01-06 23:20
Hey @L-Cafe,

Thanks for your update on this report. I know this is a bit of a hassle but can you please submit the output of your bug report as suggested in our [troubleshooting session](https://github.com/python-mode/python-mode#troubleshootingdebugging)?

**Comment by L-Cafe** [comment] 2018-01-10 17:24
Hello,

I know this is not of particular interest of anybody, but I'm currently unable to reproduce the issue reported eariler. It seems that some kind of update through Homebrew fixed it.

Once I'm able to reproduce and (hopefully fix it again) I will post the instructions.

**Comment by fmv1992** [comment] 2018-01-13 10:04
@L-Cafe,

This happens frequently. Vim can be misterious. I'm closing this.

Best :)

**Closed by fmv1992** 2018-01-13 10:04 UTC

**Comment by arnavb** [comment] 2018-10-16 20:34
Im experiencing this same issue when trying to use Python 3. Any update on this?
