### ISSUE TITLE
高亮无法正常工作

### ISSUE THREAD

**Issue by nianfouyi** [python-mode/python-mode#909] opened 2018-06-20 11:38 UTC
你做的这款插件太好了，但我在使用发现了一些小问题，我已经按文档的配置说明设置了高亮配置，但在vim里无法正确显示高亮，主要表现在等号，乘号，以及building types bulding object。所以向你请教

**Comment by jennaliu** [comment] 2018-06-20 21:23
现在的主要维护人员好像不说中文，建议用英语open issue。你是怎么设置高亮的？

**Comment by jennaliu** [comment] 2018-06-20 21:54
This issue is a duplicate of #886

**Comment by diraol** [comment] 2018-06-20 22:04
I'm sorry @luozhongxiangsi but I don't understand your language. Please, post in English (if the issue is different from what @jennaliu indicated).

**Closed as completed by diraol** 2018-06-20 22:04 UTC

**Comment by nianfouyi** [comment] 2018-06-21 08:44
OK, thank you @diraol

**Comment by nianfouyi** [comment] 2018-06-21 08:48
do you understand Chinese @jennaliu if you understanding! i  will write Chinese

**Comment by nianfouyi** [comment] 2018-06-21 08:54
我就是按着说明文档来设置高亮的，我改了color scheme,但是我又改回来，然后，现在等号高亮能正常显示 了，但是 let g:pymode_syntax_builtin_objs = g:pymode_syntax_all  和
    let g:pymode_syntax_builtin_types = g:pymode_syntax_all不能正常显示 @jennaliu

**Comment by jennaliu** [comment] 2018-06-21 15:18
In vim, run **:hi** and you will see all the highlight groups. Find the line for Type (builtin_objs are mapped to this group) and Statement (equal sign is mapped to this group). F.g.
Type           xxx ctermfg=3 gui=bold guifg=#60ff60
Check what color xxx is. The colors are defined by your color scheme.

**Comment by nianfouyi** [comment] 2018-06-22 14:33
OK，！thank you very much, I will try again.do you understanding Chinese

**Comment by jennaliu** [comment] 2018-06-22 15:14
Yes I do. But I think using the language that the maintainers understand is courtesy. And issue list is not a forum. I am just a 路人甲

**Comment by nianfouyi** [comment] 2018-06-23 15:29
谢谢你，好心的路人甲，愿你好人有好报 ，很好奇 ，你是怎么学习中文的？
