### ISSUE TITLE
python-mode with python 3.7 `imp`/`importlib` incompatibility

### ISSUE THREAD

**Issue by byebaibai** [python-mode/python-mode#916] opened 2018-07-03 11:10 UTC
When I use vim to open test.py , the Python-mode doesn't work.
I have no idea about how to solve the problem(>_<)
Here are my python mode debug file:

Error detected while processing function pymode#init:
line    2:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
-------------------------------------------------------------------------------
pymode debug msg 1: Starting debug on: 2018-07-03 18:57:46 with file /var/folders/zg/q4yfxyj93nxbrd7f0sygsdmh0000gn/T/pymode_debug_file.txt
-------------------------------------------------------------------------------
pymode debug msg 2: Operating system: Darwin
-------------------------------------------------------------------------------
pymode debug msg 3: Scriptnames:
-------------------------------------------------------------------------------
pymode debug msg 4: Pymode variables:
pymode                #1
pymode_breakpoint     #1
pymode_breakpoint_bind  <leader>b
pymode_breakpoint_cmd  import pdb; pdb.set_trace()  # XXX BREAKPOINT
pymode_debug          #1
pymode_debug_counter  #3
pymode_debug_tempfile  /var/folders/zg/q4yfxyj93nxbrd7f0sygsdmh0000gn/T/pymode_debug_file.txt
pymode_doc            #1
pymode_doc_bind        K
pymode_doc_vertical   #0
pymode_folding        #0
pymode_folding_nest_limit #1000
pymode_folding_regex   ^\s*\%(class\|def\|async\s\+def\) .\+\(:\s\+\w\)\@!
pymode_indent         #1
pymode_init           #1
pymode_lint           #1
pymode_lint_async     #1
pymode_lint_async_updatetime #1000
pymode_lint_checkers  ['pyflakes', 'pep8', 'mccabe']
pymode_lint_comment_symbol  CC
pymode_lint_cwindow   #1
pymode_lint_docs_symbol  DD
pymode_lint_error_symbol  EE
pymode_lint_ignore    []
pymode_lint_info_symbol  II

**Comment by freeyoung** [comment] 2018-07-05 14:15
Are you using Python 3.7?

**Comment by migto** [comment] 2018-07-07 04:15
this could be a python 3.7 problem, the imp warning happens in YouCompleteMe too

**Comment by mattnworb** [comment] 2018-07-19 14:13
this happens to me with Macvim installed via Homebrew, which is built against Homebrew's installed version of python 3.7.0.

**Comment by jamesrharwood** [comment] 2018-07-26 20:34
Getting same error with python 2.7.10 on Mac OS High Sierra

**Comment by fmv1992** [comment] 2018-07-26 23:56
The problem is with the `test.py` file name. I came across it a couple of times in the past. I have no idea why though...

**Comment by idvorkin** [comment] 2018-08-19 20:48
I have a repro on linux with out the test.py file name. I am also using vim 8.1/py3.7

**Comment by ricardodani** [comment] 2018-08-28 21:13
:+1:  Same here, vim found a solution and made a patch. So, if youre using vim without plugins, updating it to at least 8.1.0201 should work https://github.com/vim/vim/commit/79a494d5e2f97c10e74f92ea529552623c314422

**Comment by tammersaleh** [comment] 2018-09-06 17:34
I believe I'm still seeing this behavior with Macvim 8.1.0-280:

```
$ mvim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Sep  6 2018 09:26:40)
macOS version
Included patches: 1-280
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    +tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
+autochdir         +float             +mouse_xterm       +terminal
-autoservername    +folding           +multi_byte        +terminfo
+balloon_eval      -footer            +multi_lang        +termresponse
+balloon_eval_term +fork()            -mzscheme          +textobjects
+browse            +fullscreen        +netbeans_intg     +timers
++builtin_terms    -gettext           +num64             +title
+byte_offset       -hangul_input      +odbeditor         +toolbar
+channel           +iconv             +packages          +transparency
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua               +ruby              +writebackup
+dialog_con_gui    +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       -xpm
-ebcdic            +mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib -L.             -L /BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/libressl/lib -L/BuildRoot/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.Internal.sdk/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -liconv -framework AppKit  -pagezero_size 10000 -image_base 100000000 -L/usr/local/opt/luajit/lib -lluajit-5.1 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -framework Ruby    
```

I see the error whenever I open a python file (empty `test.py` does the trick).

```
Error detected while processing function pymode#breakpoint#init:
line   27: /must>not&exist/foo:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation f
or alternative uses
Press ENTER or type command to continue
```

Here's my python config, if relevant:

``` command
$ cat .vim/after/ftplugin/python.vim 
let g:pymode_python = 'python3'
let g:pymode_syntax_all = 1
let g:pymode_rope = 0 " Too much
let g:pymode_options = 0

setlocal formatoptions-=ta
setlocal commentstring=#%s
setlocal define=^\s*\\(def\\\\|class\\)

let g:pymode_lint = 0 " We use ALE
let b:ale_fix_on_save = 1
let b:ale_fixers = ['isort', 'autopep8', 'remove_trailing_lines', 'trim_whitespace'] 
``` 

Also, the suggested fix in vim/vim#3117 of adding:

``` vimscript
if has('python3')
  silent! python3 1
endif
```

Did not fix this issue for me.

**Comment by tammersaleh** [comment] 2018-09-06 17:40
...and it looks like a PR for this is already in the works:  python-mode/python-mode#919.  Does anyone have a workaround until that PR is merged?

**Comment by ricardodani** [comment] 2018-09-11 14:44
@tammersaleh what I meant is that VIM fixed that, but python-mode still don't.

**Comment by blayz3r** [comment] 2018-09-17 23:09
+1

**Comment by liuhonghe** [comment] 2018-11-05 10:48
Give up python3.7
Install python3.6
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/f2a764ef944b1080be64bd88dca9a1d80130c558/Formula/python.rb`

**Comment by RichyMong** [comment] 2018-11-07 02:17
+1

**Comment by mgoffin** [comment] 2018-11-07 04:36
+1

**Comment by diraol** [comment] 2018-11-07 14:12
@ricardodani @blayz3r @mgoffin @tammersaleh @RichyMong @jamesrharwood @mattnworb @migto @BaldwinHe Can you all please try and check if the current code works now?

**Comment by sulrich** [comment] 2018-11-07 14:30
yes!  this is now working.

**Closed as completed** 2018-11-08 02:24 UTC

**Comment by mattnworb** [comment] 2018-11-08 14:39
@diraol with my `.vim/bundle/python-mode` at commit 551c9d4 I no longer get the DeprecationWarning about imp, but I do see a new warning the first time I open a `.py` file:

```
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'six'
```

here is my vim version:

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 06:55:58)
macOS version
Included patches: 1-500
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.3 -lobjc
```

**Comment by liuhonghe** [comment] 2018-11-08 14:47
> @diraol with my `.vim/bundle/python-mode` at commit [551c9d4](https://github.com/python-mode/python-mode/commit/551c9d473f269d3b1ef7354506af4485bb88ba2c) I no longer get the DeprecationWarning about imp, but I do see a new warning the first time I open a `.py` file:
> 
> ```
> Error detected while processing function pymode#breakpoint#init:
> line   29:
> Traceback (most recent call last):
>   File "<string>", line 2, in <module>
> ModuleNotFoundError: No module named 'six'
> ```
> here is my vim version:
> 
> ```
> VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 06:55:58)
> macOS version
> Included patches: 1-500
> Compiled by Homebrew
> Huge version without GUI.  Features included (+) or not (-):
> +acl               +extra_search      +mouse_netterm     +tag_old_static
> +arabic            +farsi             +mouse_sgr         -tag_any_white
> +autocmd           +file_in_path      -mouse_sysmouse    -tcl
> +autochdir         +find_in_path      +mouse_urxvt       +termguicolors
> -autoservername    +float             +mouse_xterm       +terminal
> -balloon_eval      +folding           +multi_byte        +terminfo
> +balloon_eval_term -footer            +multi_lang        +termresponse
> -browse            +fork()            -mzscheme          +textobjects
> ++builtin_terms    -gettext           +netbeans_intg     +timers
> +byte_offset       -hangul_input      +num64             +title
> +channel           +iconv             +packages          -toolbar
> +cindent           +insert_expand     +path_extra        +user_commands
> -clientserver      +job               +perl              +vartabs
> +clipboard         +jumplist          +persistent_undo   +vertsplit
> +cmdline_compl     +keymap            +postscript        +virtualedit
> +cmdline_hist      +lambda            +printer           +visual
> +cmdline_info      +langmap           +profile           +visualextra
> +comments          +libcall           -python            +viminfo
> +conceal           +linebreak         +python3           +vreplace
> +cryptv            +lispindent        +quickfix          +wildignore
> +cscope            +listcmds          +reltime           +wildmenu
> +cursorbind        +localmap          +rightleft         +windows
> +cursorshape       -lua               +ruby              +writebackup
> +dialog_con        +menu              +scrollbind        -X11
> +diff              +mksession         +signs             -xfontset
> +digraphs          +modify_fname      +smartindent       -xim
> -dnd               +mouse             +startuptime       -xpm
> -ebcdic            -mouseshape        +statusline        -xsmp
> +emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
> +eval              -mouse_gpm         +syntax            -xterm_save
> +ex_extra          -mouse_jsbterm     +tag_binary
>    system vimrc file: "$VIM/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>   fall-back for $VIM: "/usr/local/share/vim"
> Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
> Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.14 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.3 -lobjc
> ```

pip install six

**Comment by blayz3r** [comment] 2018-11-08 15:18
> @ricardodani @blayz3r @mgoffin @tammersaleh @RichyMong @jamesrharwood @mattnworb @migto @BaldwinHe Can you all please try and check if the current code works now?

Works now

**Comment by diraol** [comment] 2018-11-08 15:45
That should not be necessary @liuhonghe since we have six module "hardcoded" into the project (under submodules).

That's really strange ....

**Comment by mattnworb** [comment] 2018-11-08 15:52
@diraol perhaps I updated `.vim/bundle/python-mode` incorrectly then, but here is what I see in the directory now (I have my `.vim/bundle` contents as submodules themselves):

```
[mattbrown@mattmbp python-mode]$ git submodule
 5b5cd7acbecaa9b587b07de27a3334a2ec4f2a79 submodules/astroid (astroid-2.0.4)
 159bb88843e298534e46914da242e680a1c8c47d submodules/autopep8 (v1.3.2-90-g159bb88)
 c2f5b386458cfda0aa4239f4d11b4e5e75027bda submodules/mccabe (0.6.1-19-gc2f5b38)
 566cdc0cb22e5530902e456d0b315403ebab980c submodules/pycodestyle (2.4.0-19-g566cdc0)
 eea4ca179553189a7b8a62d6085f15b50bb98e35 submodules/pydocstyle (0.4.1-431-geea4ca1)
 45fc732466056fe35c85936ff25491df7905c597 submodules/pyflakes (2.0.0-10-g45fc732)
 c01c803980b7cc18bae84c5c1845919485842221 submodules/pylama (6.0.1-297-gc01c803)
 66cb32187c040f82dd067bc0d226b2f105bf6c38 submodules/pylint (pylint-2.1.0-59-g66cb3218)
 95aa2749f978d579fda03478dece4d611c2323f9 submodules/rope (0.11.0-2-g95aa2749)
 84d07dd19523a3a41385f23a744a126d00a72c79 submodules/six (1.11.0-14-g84d07dd)
 404cab3e069cd5c2c891c19404fbd85bd285c021 submodules/snowball_py (heads/develop)

[mattbrown@mattmbp python-mode]$ git show-ref HEAD
551c9d473f269d3b1ef7354506af4485bb88ba2c refs/remotes/origin/HEAD
```

**Comment by tammersaleh** [comment] 2018-11-08 15:59
Worked for me.  I use https://github.com/junegunn/vim-plug, and had to update the `Plug` line to track `develop`:

``` vim
Plug 'python-mode/python-mode', { 'branch': 'develop' }
```

(which incidentally means I wasn't getting updates previously)

**Comment by Tsubashi** [comment] 2018-11-09 03:49
I also use plug, but have the same issue as @diraol.

**Comment by liuhonghe** [comment] 2018-11-10 07:06
sys.path  ??
```
autoload/pymode/breakpoint.vim

from pymode.libs.six import PY3
```

**Comment by diraol** [comment] 2018-11-10 12:01
Nice catch @liuhonghe !
@mattnworb can you please try the branch `fix_six_import` from [my python-mode fork](https://github.com/diraol/python-mode), please?

**Comment by diraol** [comment] 2018-11-10 12:01
@Tsubashi which issue that I have?

**Comment by Tsubashi** [comment] 2018-11-10 14:58
My apologies. I meant @mattnworb. Not sure how I mixed that one up.

If I switch to your branch, the error changes to 

```
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'pymode.six'
```

**Comment by diraol** [comment] 2018-11-12 00:24
@Tsubashi sorry, I've made a mistake on that branch.

I used `pymode.six` while I should have used `pymode.libs.six`

I've already changed that and made a push force to that branch. Please, check again. ;)
Tks!

**Comment by Tsubashi** [comment] 2018-11-12 02:02
That fixes it. Thanks!

**Comment by mattnworb** [comment] 2018-11-12 12:48
@diraol great news, I no longer get any errors using `diraol/fix_six_import` with vim!

I am afraid though that Macvim (which I install via a Homebrew cask) is giving me an error though :(

```
"foo/core.py" 62L, 1716C
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: No module named libs.six
```

here is the `:version` dump from my Macvim install:

```
:version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 14 2018 05:28:49)
macOS version
Included patches: 1-280
Compiled by travis@Traviss-Mac-1044.local
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +cmdline_compl     +emacs_tags        +iconv             +mksession         -mzscheme          +reltime           +termguicolors     +visualextra
+arabic            +cmdline_hist      +eval              +insert_expand     +modify_fname      +netbeans_intg     +rightleft         +terminal          +viminfo
+autocmd           +cmdline_info      +ex_extra          +job               +mouse             +num64             +ruby/dyn          +terminfo          +vreplace
+autochdir         +comments          +extra_search      +jumplist          +mouseshape        +odbeditor         +scrollbind        +termresponse      +wildignore
-autoservername    +conceal           +farsi             +keymap            +mouse_dec         +packages          +signs             +textobjects       +wildmenu
+balloon_eval      +cryptv            +file_in_path      +lambda            -mouse_gpm         +path_extra        +smartindent       +timers            +windows
+balloon_eval_term +cscope            +find_in_path      +langmap           -mouse_jsbterm     +perl/dyn          +startuptime       +title             +writebackup
+browse            +cursorbind        +float             +libcall           +mouse_netterm     +persistent_undo   +statusline        +toolbar           -X11
++builtin_terms    +cursorshape       +folding           +linebreak         +mouse_sgr         +postscript        -sun_workshop      +transparency      -xfontset
+byte_offset       +dialog_con_gui    -footer            +lispindent        -mouse_sysmouse    +printer           +syntax            +user_commands     +xim
+channel           +diff              +fork()            +listcmds          +mouse_urxvt       +profile           +tag_binary        +vartabs           -xpm
+cindent           +digraphs          +fullscreen        +localmap          +mouse_xterm       +python/dyn        +tag_old_static    +vertsplit         -xsmp
+clientserver      +dnd               -gettext           +lua/dyn           +multi_byte        +python3/dyn       -tag_any_white     +virtualedit       -xterm_clipboard
+clipboard         -ebcdic            -hangul_input      +menu              +multi_lang        +quickfix          -tcl               +visual            -xterm_save
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation:
clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib -L. -fstack-protector -L/usr/loca
l/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o Vim -framework Cocoa -framework Carbon       -lm  -lncurses -l
iconv -framework AppKit   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE
```

**Comment by oski89** [comment] 2018-11-20 00:09
> @Tsubashi sorry, I've made a mistake on that branch.
> 
> I used `pymode.six` while I should have used `pymode.libs.six`
> 
> I've already changed that and made a push force to that branch. Please, check again. ;)
> Tks!

Had the same issue and this fixed it. Thanks!

**Comment by typoman** [comment] 2018-12-02 22:52
I used @diraol fix and I don't get any more errors. Thanks! In case you use vim-plug, here is the way to install it:
`Plug 'diraol/python-mode', { 'branch': 'fix_six_import' }`

**Comment by glennlawyer** [comment] 2018-12-04 16:34
The @diraol "fix_six_import" branch fixed this issue for me as well. Thanks!

osx, python 3.7.1, vim8.1

In detail:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2018 06:57:16)
macOS version
Included patches: 1-500
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    -gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       -lua               +ruby              +writebackup
+dialog_con        +menu              +scrollbind        -X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       -xim
-dnd               +mouse             +startuptime       -xpm
-ebcdic            -mouseshape        +statusline        -xsmp
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -lncurses -liconv -framework AppKit   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.28.0/lib/perl5/5.28.0/darwin-thread-multi-2level/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/config-3.7m-darwin -lpython3.7m -framework CoreFoundation  -lruby.2.5.3 -lobjc
```

**Comment by RichyMong** [comment] 2018-12-05 03:17
> Nice catch @liuhonghe !
> @mattnworb can you please try the branch `fix_six_import` from [my python-mode fork](https://github.com/diraol/python-mode), please?

It works for me. Thank you so much.

**Comment by diraol** [comment] 2018-12-05 09:37
Thanks all! =)
Changes merged to the `develop` branch!

**Comment by ricardodani** [comment] 2018-12-06 13:23
Hey, still need to install manually the library six. Six is not python-default, I don't think it's a good idea to force the plugin user to install manually the six library.

**Comment by ricardodani** [comment] 2018-12-06 13:24
But when installing six manually works fine @diraol

**Comment by diraol** [comment] 2018-12-15 21:13
@ricardodani you should not need to install six manually ..... 

I do know that six is not `python-default`, and we do no force our users to install it manually. That's why six is a submodule from `python-mode` repo.

So, by correctly installing `python-mode` you already have `six` (but only under python-mode context!).
