### ISSUE TITLE
Editing long folds makes VIM really slow

### ISSUE THREAD

**Issue by aldur** [python-mode/python-mode#523] opened 2015-01-15 08:13 UTC
While editing inside a long fold (in my case an __init__ function composed of ~150 LOC) VIM freezes and becomes really sloppy. Command mode works fine as usual instead.
After profiling it I managed to discover that setting `g:pymode_folding = 0` solves my problem.
Any way I can solve this while keeping the folding functionality?

This is the output of PymodeTroubleshooting:

```
Pymode diagnostic
===================
VIM:704, OS: Darwin, multi_byte:1, pymode: 0.8.1, pymode-python: python


+python: 1
+python3: 0

VIM python paths:
-----------------
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/waitress
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/requests
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/OmniSharpServer
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/jedi
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/frozendict
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/bottle
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/ycmd/third_party/argparse
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/ycmd
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/retries
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/requests-futures
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/requests
/Users/aldur/.vim/bundle/YouCompleteMe/third_party/pythonfutures
/Users/aldur/.vim/bundle/YouCompleteMe/autoload/../third_party/ycmd
/Users/aldur/.vim/bundle/YouCompleteMe/autoload/../python
/Users/aldur/.vim/bundle/python-mode/pymode/libs2
/Users/aldur/.vim/bundle/python-mode/pymode/libs
/Users/aldur/.vim/bundle/python-mode
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-8.0-py2.7.egg
/Library/Python/2.7/site-packages/pip-1.5.2-py2.7.egg
/usr/local/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg
/usr/local/lib/python2.7/site-packages/setuptools-8.0-py2.7.egg
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python27.zip
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
/Library/Python/2.7/site-packages
/usr/local/lib/python2.7/site-packages
_vim_path_

Pymode variables:
-------------------
let pymode = 1
let pymode_breakpoint = 0
let pymode_breakpoint_bind = '<leader>b'
let pymode_doc = 1
let pymode_doc_bind = 'K'
let pymode_folding = 0
let pymode_indent = 1
let pymode_lint = 1
let pymode_lint_checkers = ['pyflakes', 'pep8', 'mccabe']
let pymode_lint_cwindow = 1
let pymode_lint_ignore = ''
let pymode_lint_message = 0
let pymode_lint_on_fly = 0
let pymode_lint_on_write = 0
let pymode_lint_select = ''
let pymode_lint_signs = 1
let pymode_motion = 1
let pymode_options = 1
let pymode_paths = []
let pymode_quickfix_maxheight = 6
let pymode_quickfix_minheight = 3
let pymode_rope = 1
let pymode_run = 1
let pymode_run_bind = '<leader>r'
let pymode_trim_whitespaces = 1
let pymode_virtualenv = 1
let pymode_virtualenv_enabled = ''
let pymode_virtualenv_path = ''
```
##

**Comment by timmow** [comment] 2015-01-15 12:27
I also ran into this issue, and solved it by using https://github.com/Konfekt/FastFold

**Comment by aldur** [comment] 2015-01-15 13:22
Thanks, it seems really better now.
I'm leaving this open just because it could still has something to do with PyMode and the way it handles folds, with other alternatives (e.g. SimpyFold) the problem doesn't appear, so maybe an improvement could appear :)

**Comment by alexdunn** [comment] 2015-01-17 21:40
@timmow :+1: Thanks a lot for this tip, it helped me a lot!

**Comment by sruggier** [comment] 2015-04-22 21:07
+1 for FastFold. Even if the real problem is in Vim, I think pymode shouldn't be knowingly setting up a configuration that causes these kinds of performance problems. Until the current fold method is improved, it would make sense to:
* disable pymode_folding by default (or enable by default only if FastFold is installed)
* add a warning in the README that unless FastFold or equivalent is installed, enabling pymode_folding comes with the risk of severe performance problems in insert mode

Finally, I want to note that if pymode weren't so useful, I wouldn't be bothering to write this comment, so thanks for that :smiley:

**Comment by zgana** [comment] 2015-05-12 16:32
Another +1 for FastFold.  I dropped fastfold.vim in my ~/vim/plugins, and I'm back to full speed.  Now I can re-enable python-mode features I had disabled, and profit even more :)  Thanks timmow.

**Comment by sqwishy** [comment] 2016-01-24 16:41
I know this has been closed for nearly a year, but I think @sruggier has a good proposal. This has been an issue regularly enough for me that I would have appreciated either of this suggestions being implemented when I started using pymode.

**Comment by raratiru** [comment] 2017-05-11 05:07
At last! `g:pymode_folding = 0` made it work. I was about to quit programming.

**Comment by jingpengw** [comment] 2017-08-22 21:35
@raratiru 's trick works for me.
put `let g:pymode_folding = 0` in `.vimrc` file works.

in case anyone is interested, corresponding documentation:
https://github.com/python-mode/python-mode/blob/33ef6c612f972a9e8e56afc3964a5717ae2c677b/doc/pymode.txt#L162

**Comment by senderle** [comment] 2017-10-23 13:17
FYI, if you're using a plugin that saves fold positions in a view -- something alone [these lines](http://vim.wikia.com/wiki/Make_views_automatic) -- you will likely need to delete all saved views as well.

**Comment by fmv1992** [comment] 2017-11-19 00:24
Folding's behavior has improved a lot since the initial opening of this issue.

I'll close it since it probably has been resolved.

**Comment by senderle** [comment] 2017-11-19 21:43
From my perspective, it hasn't been resolved. I had to turn off folding to continue using python-mode. 

I don't care that much about folding though, to be honest. You could just remove support for it and that would resolve this bug, certainly.

**Comment by fmv1992** [comment] 2017-11-20 01:33
@senderle,

I'm glad our actual bug was resolved (indeed a coding problem).

If I'm not wrong our current folding behavior is `O(n²)` with the number of
lines and it does take some time for larger files. This is undesired but
considering that people in general edit files smaller than ~500 lines it is
acceptable.

Maybe it is more adequate to change the `foldmethod` in your python files
instead of changing the whole plugin.

An autocommand (see `:help autocmd` if needed) does the trick, and I think you
can even make it conditional in terms of the number of lines your python file
has (something along the lines of `if &ft=python && lines('$') < 500 | setlocal fdm=expr`).

**Comment by senderle** [comment] 2017-11-20 19:19
I did try modifying the foldmethod, but it remained slow. 

I also posted the above in an... uncharitable frame of mind, for which I apologize. I do think this should remain open, but I also agree with you, in the sense that this may not be an urgent issue to fix.

The thing is, I honestly don't use folding *unless* I'm editing an unusually long file. I find it easy enough to navigate 500 or even 1000 lines of code. It's when I'm looking at a 5000 line script that I need folding. And of course when that happens, something has gone very wrong indeed!

**Comment by fmv1992** [comment] 2017-11-20 19:47
@senderle,

No offense taken at all :)

The folding is to help users that do like it and to be invisible for users
indifferent to it. It puzzles me that you are getting slowed by it even after
changing the foldmethod.

What I would try is:

1. Delete any permanent files related to your file (view files, history, etc).
1. After loading it use `:set fdm=marker`.
1. Be sure that this is the only view of this file. If you have it opened in
   another buffer then typing can be really slow as vim computes folding for
   nearby lines for every character typed.
1. Be sure that this is a python mode issue: try disabling the plugin and see
   if the problem goes away.

Lastly if your file is not personal I kindly ask you to either submit it here
or send me a link in order for me to reproduce this issue. I'm fixing some
folding issues at this very moment.

Best,

**Comment by senderle** [comment] 2017-11-20 23:54
When I have a moment to replicate, I'll send the file. Now that you mention it, it is *possible* that my changes to the foldmethod were overridden by an old saved view. If that turns out to be the case I'll report it here. (And with additional apologies!)

**Comment by fmv1992** [comment] 2017-11-21 02:20
No need to apologize : )

Hopefully it is not the plugin's fault!

**Comment by alphaCTzo7G** [comment] 2018-01-26 18:40
I have the same issue as well. I know Vim8 has introduced async. Do you guys use VIM8? Does it resolve or make the Folding issue better compared to VIM7.4?

**Comment by alphaCTzo7G** [comment] 2018-01-26 20:51
Just upgraded to VIM8. Theres no difference in folding times/backspace in `insert` mode. Without `FastFold`, its just as slow.

**Comment by fmv1992** [comment] 2018-01-28 20:23
Hey @alphaCTzo7G,

I didn't understand if this issue was fixed for you or not.

Folding for huge files is expected to be slow since every line has to "scan" for function definitions and some other stuff. One cannot simply determine the folding by just looking at the line itself.

I think an improvement is to implement a "lightweight folding" and use a global variable to control it. Contributions are welcome.

**Comment by senderle** [comment] 2018-01-29 14:19
I think this continues to be an issue, but it isn't trivial to fix, as @fmv1992 says. If ever have the time I'll see whether I can come up with a good fix.

**Comment by fmv1992** [comment] 2018-01-29 23:06
I don't see any suggestions on triviality anywhere on my comments.

Rather the opposite. What drew me to this project was folding in the first place and it is the issue that has cost me most in terms of time and I'm aware that the results are still scant. I wish I could take those hours back into other more pressing things in this project.

Folding is not easy in vim and specially in python where no "black and white" rules exist. Just see the code.

I'm longing for other contributors to show up.

**Comment by alphaCTzo7G** [comment] 2018-02-04 00:18
For me, `FastFold` completely solved the problem. 

My first hypothesis was that it was that `Vim7.4` didn’t have async which was causing the problem. So I installed `VIM8`. That didn’t solve the problem.

So, I installed `FastFold` and it instantly solved the problem. I wanted to doublecheck that it was indeed `FastFold` that solved the problem. So I removed it from my load path and tried it on the same file which had very slow `Insert` mode operation. Weirdly, I found that there was no problem on that day. 

Historically, my experience has been that the slowness in `Insert` mode doesn’t happen just because of the length of the file. It’s a combination of the length of the file and how long I have been editing it. Probably there is a weird interaction with the cache, if vim is storing one. So I thought I would try to reproduce the error by removing ‘FastFold` and editing in `VIM` as usual. 

Weirdly, after a few days, I was again able to reproduce the problem, after editing without `FastFold` after 3-4 days. When I loaded `FastFold` the problem vanished again, and hasn’t happened in the last week or so that I have been editing long python files  with `ViM8`.
This experiment kindof validated that the problem was not just with python-mode/.vim/YCM but how long I have been editing the file using VIM. The length of the file at start was >500 files, and is still around the same number. I have also checked with multiple python files, so its not a particular python file that has this issue. It’s a general problem.

## Solution:
Perhaps there could be 2 potential solutions:
1.	Include `FastFold` in python-mode to quickly solve the problem
2.	Use this solution that somebody pointed out by default: https://github.com/Valloric/YouCompleteMe/issues/1395#issuecomment-361446871

Fundamentally, if there is a quick and dirty solution, that solves the problem, I don’t necessarily see a reason to not to use these modifications and spend a lot of time figuring out more complex solutions. That is unless these modifications would somehow cause severe issues in future.

**Comment by senderle** [comment] 2018-02-05 20:24
@fmv1992 sorry for any confusion! I felt you were saying that this is _not_ a trivial problem, and I was _agreeing_ with you.

**Comment by Felixoid** [comment] 2018-07-11 09:53
Hi. I spent a LOT of time to investigate the problem with hangs in insert mode and wasn't able to find what is it. Maybe, is it really a good idea to enable g:pymode_folding by default only with installed `FastFold`? With the note in docs, of course.

**Comment by karoljoc** [comment] 2018-09-07 11:34
Oh my goodness.......after setting "let g:pymode_folding = 0" my vim windows are working like a Xeon again and not as a i386 👍

**Comment by kalfa** [comment] 2018-10-25 15:38
FYI what @timmow suggested is still the best solution I have found, if people prefer to have pymode_folding=1

**Closed** 2019-02-17 15:48 UTC

**Comment by AaronM04** [comment] 2019-12-07 01:41
Just curious -- why was this closed? I am on commit f94b0d7 and still experiencing this problem (without the workaround mentioned above).

**Comment by diraol** [comment] 2019-12-09 12:31
I'd say that because there is not enough hands on the project to make it happen and we have a satisfactory alternative for it very compelling in terms of DRY. Actually, I'd say that we should even remove folding from python-mode (if we have hands for it) since there are much better folding solutions around (better maintained, with better compatibility both with python and other languages too).
Does it make sense?

Also, you are using a plenty old version of python-mode. It is even attached to the wrong git branch (we are using the `develop` branch, as stated in the README.md, while you are using the `master` branch).

**Comment by diraol** [comment] 2019-12-09 12:31
@AaronM04 :point_up: (I forgot to mention you, sorry)

**Comment by AaronM04** [comment] 2019-12-10 03:56
Good to know, thanks!

I like the idea of removing folding from python-mode if there are better plugins for this. Can you tell me what other folding solutions would be better, though?

And I am not sure why I am on this commit. I'll fix that.

**Comment by diraol** [comment] 2019-12-10 13:18
Hi @AaronM04 regarding the commit, take a look at our README.md, you will find instructions there on how to properly install python-mode.

About folding, take a look at this comment: https://github.com/python-mode/python-mode/issues/523#issuecomment-362868426 (from this same issue), there is a good alternative over there ;)
