### ISSUE TITLE
"{{" in strings causes indentation outside of the string.

### ISSUE THREAD

**Issue by edliaw** [python-mode/python-mode#133] opened 2012-10-05 16:52 UTC
The error occurs when typing the following:

```
"{{"
    # This line will be indented
```

Use case:
{{ is used to escape a single curly brace in str.format() strings.
##

**Comment by brycepg** [comment] 2016-12-19 05:43
I can't reproduce this, so I'm closing. 

If anyone can, let me know your value of `foldmarker`

**Closed** 2016-12-19 05:44 UTC
