### ISSUE TITLE
Python-mode not working in conda environment

### ISSUE THREAD

**Issue by fjhheras** [python-mode/python-mode#989] opened 2019-02-04 16:04 UTC
I installed python-mode in manual mode following instructions on the readme. It works fine outside the conda environment, but when a conda environment is activated, I see the following errors when opening vim:

```Error detected while processing /home/USER/.vim/autoload/pymode/virtualenv.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/USER/.vim/pymode/virtualenv.py", line 7, in <module>
    from .environment import env
  File "/home/USER/.vim/pymode/environment.py", line 10, in <module>
    from ._compat import PY2
  File "/home/USER/.vim/pymode/_compat.py", line 26, in <module>
    from queue import Queue # noqa
  File "/home/USER/miniconda3/envs/algebra/lib/python3.7/queue.py", line 16, in <module>
    from _queue import Empty
ImportError: /home/USER/miniconda3/envs/algebra/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyList_New
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/USER/.vim/pymode/libs/six.py", line 631, in <module>
    import struct
  File "/home/USER/miniconda3/envs/algebra/lib/python3.7/struct.py", line 13, in <module>
    from _struct import *
ImportError: /home/USER/miniconda3/envs/algebra/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _PyFloat_Pack4
Error detected while processing /home/USER/.vim/ftplugin/python/pymode.vim:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/USER/.vim/pymode/utils.py", line 9, in <module>
    from ._compat import StringIO
  File "/home/USER/.vim/pymode/_compat.py", line 26, in <module>
    from queue import Queue # noqa
  File "/home/USER/miniconda3/envs/algebra/lib/python3.7/queue.py", line 16, in <module>
    from _queue import Empty
ImportError: /home/USER/miniconda3/envs/algebra/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyList_New
 ```

Any idea about how to solve this? I have tried all combinations of removing and adding the following to my vimrc:

```
let g:pymode_python = 'python3'
let g:pymode_virtualenv_path = "/home/USER/miniconda3/algebra"
```

**Comment by ToniDS** [comment] 2019-02-05 17:13
Is it possible that your environment uses python3.7? For me, my conda envs with Python 3.6 actually still work, it's just the envs with python3.7 that don't work. I haven't found a solution, though, unfortunately.

**Comment by diraol** [comment] 2019-02-05 17:18
Hi,
can you follow our [Troubleshooting section](https://github.com/python-mode/python-mode#troubleshootingdebugging) and provide more information for us to help you? (This is for both of you @fjhheras and @ToniDS, since we have fixed problems regarding python versions very recently)

**Comment by virtual-expo** [comment] 2019-02-27 14:23
Hi all,
I am facing the same issue: python-mode is not working anymore when a conda environment is activated. Here are the logs, following the troubleshooting section:

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"reco1.py" 99L, 3429C
Error detected while processing /home/claire/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/claire/.vim/bundle/python-mode/pymode/virtualenv.py", line 7, in <module>
    from .environment import env
  File "/home/claire/.vim/bundle/python-mode/pymode/environment.py", line 10, in <module>
    from ._compat import PY2
  File "/home/claire/.vim/bundle/python-mode/pymode/_compat.py", line 26, in <module>
    from queue import Queue # noqa
  File "/home/claire/miniconda3/lib/python3.7/queue.py", line 16, in <module>
    from _queue import Empty
ImportError: /home/claire/miniconda3/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyList_New
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/claire/.vim/bundle/python-mode/pymode/libs/six.py", line 631, in <module>
    import struct
  File "/home/claire/miniconda3/lib/python3.7/struct.py", line 13, in <module>
    from _struct import *
ImportError: /home/claire/miniconda3/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _PyFloat_Pack4
Error detected while processing /home/claire/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/claire/.vim/bundle/python-mode/pymode/utils.py", line 9, in <module>
    from ._compat import StringIO
  File "/home/claire/.vim/bundle/python-mode/pymode/_compat.py", line 26, in <module>
    from queue import Queue # noqa
  File "/home/claire/miniconda3/lib/python3.7/queue.py", line 16, in <module>
    from _queue import Empty
ImportError: /home/claire/miniconda3/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyList_New
line  239:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/claire/miniconda3/lib/python3.7/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/home/claire/miniconda3/lib/python3.7/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: /home/claire/miniconda3/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyArg_Parse
```

**Comment by virtual-expo** [comment] 2019-02-27 14:49
I found a dirty solution.
Since the problem is coming from lib-dynload in the miniconda python install, I made a symbolic link from my system lib-dynload directory.
```
cd ~/miniconda3/envs/MLProjects/lib/python3.7
ln -s /usr/lib/python3.7/lib-dynload .
```

**Comment by diraol** [comment] 2019-03-07 00:39
So, it seems that the problem is that your VIM was built with python dynamic link support, but your conda environment does not have the dependencies for that. Is that right @claire-w ?

**Comment by virtual-expo** [comment] 2019-03-07 11:05
Yes, you are totally right @diraol . The python executable in my conda environment is statically linked to libpython, which is causing the issue.

According to this [issue](https://github.com/conda-forge/python-feedstock/issues/222), python is dynamically linked to libpython in a conda environment with python 3.6. I created such an environment and tested the plugin, which perfectly works.
```
conda create --name test python=3.6
conda activate test
```

**Comment by diraol** [comment] 2019-03-07 11:21
Nice @claire-w, thanks for the explanation! =)

So can we close this issue?
@fjhheras have you seen @claire-w comments? Does it work for you?

**Comment by fjhheras** [comment] 2019-03-07 11:31
Thank you @claire-w for your tests (and for submitting the right logs following the troubleshooting section, which for some reason I was unable to).

My conda environment is indeed python 3.7. I can confirm that in an enviroment with python 3.6, (a manually-installed) python-mode works. I have not tried the symbolic link, but what I did try was to install python-mode with Vundle, and it works (even with version 3.7). Does this make sense?

**Comment by diraol** [comment] 2019-03-08 10:18
Hum, regarding this issue (conda envs) the way you install python-mode shouldn't make any difference.

But the important is that it is working! ;)

If you need any further assistance regarding this issue just let us know. I'm closing the issue for now, but we can reopen it if needed.

**Closed as completed by diraol** 2019-03-08 10:18 UTC

**Comment by fjhheras** [comment] 2019-03-21 13:58
I am afraid I am still having problems with my system, and now I think it is a different problem to the one @claire-w had. My conda has python version 3.7 in base. If I create an environment with python 3.7, I find that python-mode works with no problems.

However, if I create an environment in 3.6 (and I need this version for certain applications), I have this error:

```
Error detected while processing /home/USER/.vim/bundle/python-mode/autoload/pymode/virtualenv.vim:
line    3:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/USER/.vim/bundle/python-mode/pymode/virtualenv.py", line 7, in <module>
    from .environment import env
  File "/home/USER/.vim/bundle/python-mode/pymode/environment.py", line 10, in <module>
    from ._compat import PY2
  File "/home/USER/.vim/bundle/python-mode/pymode/_compat.py", line 26, in <module>
    from queue import Queue # noqa
  File "/home/USER/miniconda3/lib/python3.7/queue.py", line 16, in <module>
    from _queue import Empty
ImportError: /home/USER/miniconda3/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyList_New
Error detected while processing function pymode#breakpoint#init:
line   29:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/home/USER/.vim/bundle/python-mode/pymode/libs/six.py", line 631, in <module>
    import struct
  File "/home/USER/miniconda3/lib/python3.7/struct.py", line 13, in <module>
    from _struct import *
ImportError: /home/USER/miniconda3/lib/python3.7/lib-dynload/_struct.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _PyFloat_Pack4
Error detected while processing /home/USER/.vim/bundle/python-mode/ftplugin/python/pymode.vim:
line   25:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/USER/.vim/bundle/python-mode/pymode/utils.py", line 9, in <module>
    from ._compat import StringIO
  File "/home/USER/.vim/bundle/python-mode/pymode/_compat.py", line 26, in <module>
    from queue import Queue # noqa
  File "/home/USER/miniconda3/lib/python3.7/queue.py", line 16, in <module>
    from _queue import Empty
ImportError: /home/USER/miniconda3/lib/python3.7/lib-dynload/_queue.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyList_New
line  239:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/USER/miniconda3/lib/python3.7/tempfile.py", line 45, in <module>
    from random import Random as _Random
  File "/home/USER/miniconda3/lib/python3.7/random.py", line 42, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: /home/USER/miniconda3/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyArg_Parse
```
I cannot do the symbolic link that @claire-w proposed (the file already exists). 

My vim is a precompiled version from Arch Linux. When running
`python3 import sys; print(sys.version)`
It always returns
`3.7.2 (default, Jan 10 2019, 23:51:51)
[GCC 8.2.1 20181127] `

Independently of what conda environment I call it from. Maybe I am telling vim or python-mode to use the wrong python? Or that the version my vim is compiled against is 3.7 and I am using it for 3.6?

**Comment by diraol** [comment] 2019-03-21 14:56
@fjhheras may be you need to compile your vim with 'dynamic python' version instead of setting a specific one.

But I'm not sure if this is the real issue.
Try the following in "multiple envs":
`PymodePython import sys; print(sys.version)`

Anyway, for me, it looks more a problem with Conda than with python-mode or vim.

**Comment by fjhheras** [comment] 2019-03-21 15:15
The output of that command is always
```
3.7.2 (default, Jan 10 2019, 23:51:51) 
[GCC 8.2.1 20181127]
```
independently on the conda environment I run it from.

Funnily enough, when I add 
`let g:pymode_python = 'python'`
instead of 
`let g:pymode_python = 'python3'`
I do not get any errors and pymode works (except of course I get linting, packages, etc, for python 2)

I do not compile vim myself: I am using a precompiled version from Arch Linux. My precompiled version has been compiled with dynamic version, or at least when running

`vim --version`

it contains
```
 +python/dyn +python3/dyn 
```
