### ISSUE TITLE
Can't load it into vim, lin.py complain most

### ISSUE THREAD

**Issue by Jzarecta** [python-mode/python-mode#951] opened 2018-10-15 00:04 UTC
Getting a bunch of errors when trying to get the python-mode module with their submodules in pylama.  I am on vim 8.1.374 in Arch Linux. 
```
Error detected while processing function pymode#breakpoint#init:
line   21:
/must>not&exist/foo:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
Traceback (most recent call last):
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "<string>", line 1, in <module>
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jza/.vim/bundle/python-mode/pymode/lint.py", line 9, in <module>
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pylama.lint.extensions import LINTERS
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jza/.vim/bundle/python-mode/pymode/libs/pylama/lint/extensions.py", line 44, in <module>
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    from pkg_resources import iter_entry_points
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jza/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3084, in <module>
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    @_call_aside
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jza/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3070, in _call_aside
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    f(*args, **kwargs)
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jza/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3109, in _initialize_master_working_set
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jza/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 965, in subscribe
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    callback(dist)
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
  File "/home/jza/.vim/bundle/python-mode/pymode/libs/pkg_resources/__init__.py", line 3109, in <lambda>
Press ENTER or type command to continue
Error detected while processing /home/jza/.vim/bundle/python-mode/autoload/pymode/lint.vim:
line    1:
    add_activation_listener(lambda dist: dist.activate())
Press ENTER or type command to continue
```

**Comment by lieryan** [comment] 2018-11-06 08:12
Possible duplicate of:

- https://github.com/python-mode/python-mode/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+imp
- https://github.com/python-mode/python-mode/issues/915
- https://github.com/python-mode/python-mode/issues/916

**Comment by diraol** [comment] 2018-11-07 14:06
I may be fixed. Please, try with the newer version.

**Closed as completed** 2018-11-07 14:06 UTC
